level1 = [
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P              K                 P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P       PPPPPPPPPPP              P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                E",
        "PFFFFFFFFFFFFFFFFFFFFFFFFFLFFFFFFP",]

level2 = [
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  PPPPPP",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       E",
        "PFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFP",]
