level1 = [
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P              K                 P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P       PPPPPPPPPPP              P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                E",
        "PFFFFFFFFFFFFFFFFFFFFFFFFFLFFFFFFP",]

level2 = [
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P             FFFFFFFFFFFFFFF    P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P     FFFFFFFFFFFF               P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P       PPPPPPPPPPP              P",
        "P                                P",
        "P                                P",
        "P                                P",
        "P                                P",
        "PFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFP",]
