level1 = [
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B             P                                                                                                       B",
        "B                                                                                                                     B",
        "B                                                                                                                     B",
        "B       P   BPBPB                                                                                                     B",
        "B                                          P                                                                          B",
        "B                         P    P      P                BPB                                                            B",
        "B                   P     P    P      P                                                                               E",
        "BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  FFFFFFFFFFFFFFFFF  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB",
        "BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  FFFFFFFFFFFFFFFFF  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB",]

level2 = [
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  P",
        "P                                                                                                                  PPPPPP",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       P",
        "P                                                                                                                       E",
        "PFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPFP",]
